// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: remote/v1/remote.proto

package remotev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result int32

const (
	Result_RESULT_OK Result = 0
	// Auth result
	Result_RESULT_AUTH_TOKEN_INVALID Result = 1
	// Tunnel result
	Result_RESULT_TUNNEL_PROTOCOL_UNSUPPORTED Result = 101
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0:   "RESULT_OK",
		1:   "RESULT_AUTH_TOKEN_INVALID",
		101: "RESULT_TUNNEL_PROTOCOL_UNSUPPORTED",
	}
	Result_value = map[string]int32{
		"RESULT_OK":                          0,
		"RESULT_AUTH_TOKEN_INVALID":          1,
		"RESULT_TUNNEL_PROTOCOL_UNSUPPORTED": 101,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_v1_remote_proto_enumTypes[0].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_remote_v1_remote_proto_enumTypes[0]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_remote_v1_remote_proto_rawDescGZIP(), []int{0}
}

type TunnelProtocol int32

const (
	TunnelProtocol_TUNNEL_PROTOCOL_UDP TunnelProtocol = 0
	TunnelProtocol_TUNNEL_PROTOCOL_TCP TunnelProtocol = 1
)

// Enum value maps for TunnelProtocol.
var (
	TunnelProtocol_name = map[int32]string{
		0: "TUNNEL_PROTOCOL_UDP",
		1: "TUNNEL_PROTOCOL_TCP",
	}
	TunnelProtocol_value = map[string]int32{
		"TUNNEL_PROTOCOL_UDP": 0,
		"TUNNEL_PROTOCOL_TCP": 1,
	}
)

func (x TunnelProtocol) Enum() *TunnelProtocol {
	p := new(TunnelProtocol)
	*p = x
	return p
}

func (x TunnelProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_v1_remote_proto_enumTypes[1].Descriptor()
}

func (TunnelProtocol) Type() protoreflect.EnumType {
	return &file_remote_v1_remote_proto_enumTypes[1]
}

func (x TunnelProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelProtocol.Descriptor instead.
func (TunnelProtocol) EnumDescriptor() ([]byte, []int) {
	return file_remote_v1_remote_proto_rawDescGZIP(), []int{1}
}

// Auth
type AuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TunIp    string `protobuf:"bytes,2,opt,name=tun_ip,json=tunIp,proto3" json:"tun_ip,omitempty"`
	Token    string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_v1_remote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_remote_v1_remote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_remote_v1_remote_proto_rawDescGZIP(), []int{0}
}

func (x *AuthReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthReq) GetTunIp() string {
	if x != nil {
		return x.TunIp
	}
	return ""
}

func (x *AuthReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// AuthRsp
type AuthRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  Result `protobuf:"varint,1,opt,name=result,proto3,enum=remote.v1.Result" json:"result,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AuthRsp) Reset() {
	*x = AuthRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_v1_remote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRsp) ProtoMessage() {}

func (x *AuthRsp) ProtoReflect() protoreflect.Message {
	mi := &file_remote_v1_remote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRsp.ProtoReflect.Descriptor instead.
func (*AuthRsp) Descriptor() ([]byte, []int) {
	return file_remote_v1_remote_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRsp) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

func (x *AuthRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TunnelReq
type TunnelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proto  TunnelProtocol `protobuf:"varint,1,opt,name=proto,proto3,enum=remote.v1.TunnelProtocol" json:"proto,omitempty"`
	Port   int32          `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Egress string         `protobuf:"bytes,3,opt,name=egress,proto3" json:"egress,omitempty"`
}

func (x *TunnelReq) Reset() {
	*x = TunnelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_v1_remote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelReq) ProtoMessage() {}

func (x *TunnelReq) ProtoReflect() protoreflect.Message {
	mi := &file_remote_v1_remote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelReq.ProtoReflect.Descriptor instead.
func (*TunnelReq) Descriptor() ([]byte, []int) {
	return file_remote_v1_remote_proto_rawDescGZIP(), []int{2}
}

func (x *TunnelReq) GetProto() TunnelProtocol {
	if x != nil {
		return x.Proto
	}
	return TunnelProtocol_TUNNEL_PROTOCOL_UDP
}

func (x *TunnelReq) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TunnelReq) GetEgress() string {
	if x != nil {
		return x.Egress
	}
	return ""
}

type TunnelRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result Result         `protobuf:"varint,1,opt,name=result,proto3,enum=remote.v1.Result" json:"result,omitempty"`
	Proto  TunnelProtocol `protobuf:"varint,2,opt,name=proto,proto3,enum=remote.v1.TunnelProtocol" json:"proto,omitempty"`
	Port   int32          `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *TunnelRsp) Reset() {
	*x = TunnelRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_v1_remote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelRsp) ProtoMessage() {}

func (x *TunnelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_remote_v1_remote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelRsp.ProtoReflect.Descriptor instead.
func (*TunnelRsp) Descriptor() ([]byte, []int) {
	return file_remote_v1_remote_proto_rawDescGZIP(), []int{3}
}

func (x *TunnelRsp) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

func (x *TunnelRsp) GetProto() TunnelProtocol {
	if x != nil {
		return x.Proto
	}
	return TunnelProtocol_TUNNEL_PROTOCOL_UDP
}

func (x *TunnelRsp) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Ping/Pong/ConnectionClose/BadFrame
// Currently these are empty messages.
type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_v1_remote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_remote_v1_remote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_remote_v1_remote_proto_rawDescGZIP(), []int{4}
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_v1_remote_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_remote_v1_remote_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_remote_v1_remote_proto_rawDescGZIP(), []int{5}
}

type ConnectionClose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConnectionClose) Reset() {
	*x = ConnectionClose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_v1_remote_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionClose) ProtoMessage() {}

func (x *ConnectionClose) ProtoReflect() protoreflect.Message {
	mi := &file_remote_v1_remote_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionClose.ProtoReflect.Descriptor instead.
func (*ConnectionClose) Descriptor() ([]byte, []int) {
	return file_remote_v1_remote_proto_rawDescGZIP(), []int{6}
}

type BadFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BadFrame) Reset() {
	*x = BadFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_v1_remote_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BadFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadFrame) ProtoMessage() {}

func (x *BadFrame) ProtoReflect() protoreflect.Message {
	mi := &file_remote_v1_remote_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadFrame.ProtoReflect.Descriptor instead.
func (*BadFrame) Descriptor() ([]byte, []int) {
	return file_remote_v1_remote_proto_rawDescGZIP(), []int{7}
}

var File_remote_v1_remote_proto protoreflect.FileDescriptor

var file_remote_v1_remote_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x22, 0x53, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74,
	0x75, 0x6e, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x75, 0x6e,
	0x49, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4e, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x68, 0x0a, 0x09, 0x54, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x2f, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x7b, 0x0a, 0x09, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x73, 0x70, 0x12,
	0x29, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2f, 0x0a, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x06, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x22,
	0x11, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x22, 0x0a, 0x0a, 0x08, 0x42, 0x61, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x2a, 0x5e,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x53, 0x55,
	0x4c, 0x54, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x52, 0x45, 0x53, 0x55, 0x4c,
	0x54, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x26, 0x0a, 0x22, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54,
	0x5f, 0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c,
	0x5f, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x65, 0x2a, 0x42,
	0x0a, 0x0e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x17, 0x0a, 0x13, 0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f,
	0x43, 0x4f, 0x4c, 0x5f, 0x55, 0x44, 0x50, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x55, 0x4e,
	0x4e, 0x45, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x54, 0x43, 0x50,
	0x10, 0x01, 0x42, 0x9d, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x61, 0x63, 0x63, 0x2d, 0x67, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x52, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x3a, 0x3a,
	0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_remote_v1_remote_proto_rawDescOnce sync.Once
	file_remote_v1_remote_proto_rawDescData = file_remote_v1_remote_proto_rawDesc
)

func file_remote_v1_remote_proto_rawDescGZIP() []byte {
	file_remote_v1_remote_proto_rawDescOnce.Do(func() {
		file_remote_v1_remote_proto_rawDescData = protoimpl.X.CompressGZIP(file_remote_v1_remote_proto_rawDescData)
	})
	return file_remote_v1_remote_proto_rawDescData
}

var file_remote_v1_remote_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_remote_v1_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_remote_v1_remote_proto_goTypes = []any{
	(Result)(0),             // 0: remote.v1.Result
	(TunnelProtocol)(0),     // 1: remote.v1.TunnelProtocol
	(*AuthReq)(nil),         // 2: remote.v1.AuthReq
	(*AuthRsp)(nil),         // 3: remote.v1.AuthRsp
	(*TunnelReq)(nil),       // 4: remote.v1.TunnelReq
	(*TunnelRsp)(nil),       // 5: remote.v1.TunnelRsp
	(*Ping)(nil),            // 6: remote.v1.Ping
	(*Pong)(nil),            // 7: remote.v1.Pong
	(*ConnectionClose)(nil), // 8: remote.v1.ConnectionClose
	(*BadFrame)(nil),        // 9: remote.v1.BadFrame
}
var file_remote_v1_remote_proto_depIdxs = []int32{
	0, // 0: remote.v1.AuthRsp.result:type_name -> remote.v1.Result
	1, // 1: remote.v1.TunnelReq.proto:type_name -> remote.v1.TunnelProtocol
	0, // 2: remote.v1.TunnelRsp.result:type_name -> remote.v1.Result
	1, // 3: remote.v1.TunnelRsp.proto:type_name -> remote.v1.TunnelProtocol
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_remote_v1_remote_proto_init() }
func file_remote_v1_remote_proto_init() {
	if File_remote_v1_remote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_remote_v1_remote_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_v1_remote_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AuthRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_v1_remote_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TunnelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_v1_remote_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TunnelRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_v1_remote_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_v1_remote_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_v1_remote_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ConnectionClose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_v1_remote_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*BadFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_remote_v1_remote_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remote_v1_remote_proto_goTypes,
		DependencyIndexes: file_remote_v1_remote_proto_depIdxs,
		EnumInfos:         file_remote_v1_remote_proto_enumTypes,
		MessageInfos:      file_remote_v1_remote_proto_msgTypes,
	}.Build()
	File_remote_v1_remote_proto = out.File
	file_remote_v1_remote_proto_rawDesc = nil
	file_remote_v1_remote_proto_goTypes = nil
	file_remote_v1_remote_proto_depIdxs = nil
}
